apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include "app.fullname" . }}-pdb"
  labels:
    app: "{{ include "app.name" . }}"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "{{ include "app.name" . }}"