apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "app.fullname" . }}-role"
  labels:
    app: "{{ include "app.name" . }}"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "app.fullname" . }}-rb"
  labels:
    app: "{{ include "app.name" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "app.fullname" . }}-role"
subjects:
  - kind: ServiceAccount
    name: {{ include "app.fullname" . }}
