---
- name: Installer unzip
  apt:
    name: unzip
    state: present

- name: Télécharger et installer AWS CLI v2
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -o awscliv2.zip
    sudo ./aws/install --update
  args:
    creates: /usr/local/bin/aws